export const ADD_TICKET_REQUEST = "ADD_TICKET_REQUEST"
export const ADD_TICKET_SUCCESS = "ADD_TICKET_SUCCESS"
export const ADD_TICKET_FAIL = "ADD_TICKET_FAIL"


export const SHOW_TICKET_REQUEST = "SHOW_TICKET_REQUEST"
export const SHOW_TICKET_SUCCESS = "SHOW_TICKET_SUCCESS"
export const SHOW_TICKET_FAIL = "SHOW_TICKET_FAIL"
